# Generated by Django 3.0.9 on 2020-11-23 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='active',
        ),
    ]
