# Generated by Django 3.0.9 on 2020-11-24 13:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0002_auto_20201123_1025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Klasa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulli', models.CharField(max_length=150)),
                ('pershkrimi', models.TextField(max_length=200, null=True)),
                ('imazhi', models.ImageField(default='cat_images/default.jpg', upload_to='cat_images')),
            ],
        ),
        migrations.CreateModel(
            name='Lendet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('titulli', models.CharField(max_length=30)),
                ('pershkrimi', models.TextField(max_length=400)),
                ('krijuar_me', models.DateTimeField(auto_now=True)),
                ('imazhi_lendes', models.ImageField(default='default.jpg', upload_to='kurs_images')),
                ('klasa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Klasa')),
                ('krijues', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('titulli', models.CharField(max_length=30)),
                ('video_id', models.CharField(max_length=11)),
                ('pozicioni', models.IntegerField()),
                ('lenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Lendet')),
            ],
        ),
        migrations.DeleteModel(
            name='classes',
        ),
    ]
